### PR TITLE
fix(process): use dbus-send on linux to trigger screensave and/or lock the screen

### PR DESCRIPTION
**Pull request by floriangosse**
A way to change the lock screen/screensaver state for newer systems.

### CODE REVIEW

**Comment by bayleedev** [comment]
this is an alternative to #2 which would be more generic?

**Comment by bayleedev** [comment]
cc @marcosnils

**Comment by marcosnils** [comment]
> this is an alternative to #2 which would be more generic?

nope, it still gnome dependent. I believe the best approach would be to add configurations per window manager (http://askubuntu.com/a/227669/162352) and also to allow overrides for some specific cases

**Comment by bayleedev** [comment]
Closing this in favor of a over-writeable configuration.

**Pull request closed without merging**
