### PR TITLE
Update linux lock command to be more generic

### PR DESCRIPTION
**Pull request by marcosnils**

### CODE REVIEW

**Comment by bayleedev** [comment]
Nice, let me try this out [:

**Comment by floriangosse** [comment]
I looks like that the command is not available on an Ubuntu system with Gnome installed. But I realize that my solution (#4) is also to specific to a desktop environment.

**Comment by marcosnils** [comment]
> I looks like that the command is not available on an Ubuntu system with Gnome installed. 

You're right, seems like `dm-tool` is part of lightdm which is the window manager that I use. Seems like allow overriding seems the best option (https://github.com/tinytacoteam/zazu-system/issues/3)

> But I realize that my solution (#4) is also to specific to a desktop environment.

yup.

**Comment by bayleedev** [comment]
Closing this in favor of overwrite-able commands.

**Pull request closed without merging**
